# Generated by Django 5.2.18 on 2026-10-06 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('issue_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('issue_logged', 'Issue Logged'), ('update', 'Update'), ('landlord_contact', 'Landlord Contact'), ('deadline_set', 'Deadline Set'), ('letter_sent', 'Letter Sent'), ('correction', 'Correction')], max_length=32)),
                ('author', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.household')),
            ],
            options={
                'ordering': ['household_id', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('household', 'seq'), name='uniq_household_seq')],
            },
        ),
    ]
